- hosts: lempstack
  become: true
  become_user: root

  tasks:
    - name: set shecan as netplan nameservers
      ansible.builtin.copy:
        src: data/00-netcfg.yaml
        dest: /etc/netplan/00-netplan.yml

    - name: accept changes in netplan
      command: "netplan apply"
      ignore_errors: true

    - name: uninstall old docker versions
      apt:
        name:
          [
            docker,
            docker-engine,
            docker.io,
            containerd,
            runc
          ]
        state: absent
        update_cache: yes

    - name: set up the repository
      apt:
        name:
          [
            apt-transport-https,
            ca-certificates,
            curl,
            gnupg,
            lsb-release,
            software-properties-common
          ]
        state: latest
        update_cache: yes
