- hosts: lempstack
  become: true
  become_user: root

  vars_files:
    - data/variables.yml

  vars_prompt:
    - name: "docker_username"
      prompt: "Enter your docker registry username"
      private: no
    - name: "docker_password"
      prompt: "Enter your docker registry password"
      private: yes

  tasks:
    - name: set shecan as netplan nameservers
      ansible.builtin.copy:
        src: data/00-netcfg.yaml
        dest: /etc/netplan/00-netplan.yml

    - name: accept changes in netplan
      command: "netplan apply"
      ignore_errors: true

    - name: uninstall old docker versions
      apt:
        name:
          [
            docker,
            docker-engine,
            docker.io,
            containerd,
            runc
          ]
        state: absent
        update_cache: yes

    - name: set up the repository
      apt:
        name:
          [
            apt-transport-https,
            ca-certificates,
            curl,
            gnupg,
            lsb-release,
            software-properties-common
          ]
        state: latest
        update_cache: yes

    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present
      ignore_errors: true

    - name: Add Docker stable repository.
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/li>
        state: present
        update_cache: yes

    - name: install docker engine
      apt:
        name:
          [
            docker-ce,
            docker-ce-cli,
            containerd.io
          ]
        state: latest
        update_cache: yes

    - name: add ubuntu user to docker group
      shell: "usermod -aG docker ubuntu"

    - name: clone git repository
      git:
        repo: "https://github.com/mah54/lemp-monitor-dockerizing.git"
        dest: /home/ubuntu/lemp-monitor-dockerizing

    - name: install docker_login ansible module prerequisites
      apt:
        name:
          [
            python3,
            python3-pip,
          ]
        state: latest
        update_cache: yes

    - name: install docker pip
      pip:
        name: docker

    - name: log into docker registry
      docker_login:
        registry_url: "{{ docker_registry }}"
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: yes

    - name: install docker-compose
      shell: 'curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m>

    - name: set executing permissions to docker-compose
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        state: touch
        mode: +x

    - name: tear down existing services
      shell: "cd /home/ubuntu/lemp-monitor-dockerizing && docker-compose down"

    - name: create and start services
      shell: "cd /home/ubuntu/lemp-monitor-dockerizing && docker-compose up -d"
