services:
  db:
    image: $MYSQL_SERVER
    container_name: database
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp-net

  php-fpm-wordpress:
    image: $PHP_FPM
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - www:/var/www/wordpress
    ports:
      - 9000:9000
    networks:
      - wp-net
    
  web:
    image: $WEB_SERVER
    container_name: nginx
    restart: always
    depends_on:
      - php-fpm-wordpress
    volumes:
      - www:/var/www/wordpress
    ports:
      - 80:80
    networks:
      - wp-net

networks:
  wp-net:
    driver: bridge

volumes:
  database:
  www:
