- hosts: lempstack
  become: true
  become_user: root

  tasks:
    - name: set shecan as netplan nameservers
      ansible.builtin.copy:
        src: data/00-netcfg.yaml
        dest: /etc/netplan/00-netplan.yml

    - name: accept changes in netplan
      command: "netplan apply"
      ignore_errors: true

    - name: uninstall old docker versions
      apt:
        name:
          [
            docker,
            docker-engine,
            docker.io,
            containerd,
            runc
          ]
        state: absent
        update_cache: yes

    - name: set up the repository
      apt:
        name:
          [
            apt-transport-https,
            ca-certificates,
            curl,
            gnupg,
            lsb-release,
            software-properties-common
          ]
        state: latest
        update_cache: yes

    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present
      ignore_errors: true

    - name: Add Docker stable repository.
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/li>
        state: present
        update_cache: yes

    - name: install docker engine
      apt:
        name:
          [
            docker-ce,
            docker-ce-cli,
            containerd.io
          ]
        state: latest
        update_cache: yes
